# Generated by Django 6.0 on 2025-12-24 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rate', models.FloatField()),
                ('unit', models.CharField(choices=[('inch', 'Per Inch'), ('sq_inch', 'Per Square Inch'), ('sq_ft', 'Per Square Foot')], max_length=10)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
